universe = vanilla
log = logs/$(pdb_name).log
error = logs/$(pdb_name).err
output = logs/$(pdb_name).out

executable = run.sh
arguments = $(pdb_name)

environment = "HF_TOKEN=<your_hf_token_here>"

request_cpus = 2
request_memory = 16GB
request_disk = 10GB

requirements = (HasCHTCStaging == true)

transfer_input_files = run.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_output_files = $(pdb_name)-Dyna1.csv, $(pdb_name)-Dyna1.pdb

queue pdb_name from pdb_list.txt
